# Generated by Django 5.1.2 on 2024-11-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_valor_factura_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='forma_pago',
        ),
    ]
