# Generated by Django 5.1.2 on 2024-10-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('tipo_comprobante', models.CharField(max_length=2)),
                ('forma_pago', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
