# Generated by Django 5.1.2 on 2024-11-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='valor',
            new_name='value',
        ),
    ]
